services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - websocket-server

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/taskmanager
      - JWT_SECRET=supersecret
    depends_on:
      postgres:
        condition: service_healthy
      service-worker:
        condition: service_started
      websocket-server:
        condition: service_started

  service-worker:
    build: ./service-worker
    ports:
      - "8000:8000"
    environment:
      - OPENWEATHER_API_KEY=d6d41b6040d90825031dd1406260f6d9
    depends_on:
      - redis

  websocket-server:
    build: ./websocket-server
    ports:
      - "3001:3001"
    environment:
      - JWT_SECRET=supersecret

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=taskmanager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d taskmanager"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
